name: Trigger CircleCI Pipeline
description: Trigger the CircleCI pipeline for a given branch as if new changes had been pushed to it
branding:
  icon: share-2
  color: gray-dark

inputs:
  circleci-token:
    required: true
    description: The access token used to trigger the pipeline
  repository:
    required: true
    description: The repository to trigger the pipeline for
    default: ${{ github.repository }}
  branch:
    required: true
    description: The branch to trigger the pipeline for
    default: ${{ github.head_ref }}
  parameters:
    required: true
    description: The pipeline parameters to pass to the triggered pipeline (JSON)
    default: '{}'

runs:
  using: composite
  steps:
    - name: Trigger CircleCI Pipeline
      uses: promiseofcake/circleci-trigger-action@v.1.2.2
      with:
        user-token: ${{ inputs.circleci-token }}
        project-slug: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
        payload: ${{ inputs.parameters }}
